kind: curvefs
global:
  user: curve
  ssh_port: 22
  private_key_file: /home/curve/.ssh/id_rsa
  report_usage: true
  data_dir: /home/${user}/curvefs/data/${service_role}${service_host_sequence}
  log_dir: /home/${user}/curvefs/logs/${service_role}${service_host_sequence}
  container_image: opencurvedocker/curvefs:latest
  s3.ak: minioadmin
  s3.sk: minioadmin
  s3.endpoint: http://127.0.0.1:9000
  s3.bucket_name: <>
  variable:
    target: 10.0.1.1

etcd_services:
  config:
    listen.ip: ${target}
    listen.port: 2380${service_host_sequence}         # 23800,23801,23802
    listen.client_port: 2379${service_host_sequence}  # 23790,23791,23792
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}

mds_services:
  config:
    listen.ip: ${target}
    listen.port: 670${service_host_sequence}        # 6700,6701,6702
    listen.dummy_port: 770${service_host_sequence}  # 7700,7701,7702
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}

metaserver_services:
  config:
    listen.ip: ${target}
    listen.port: 680${service_host_sequence}  # 6800,6801,6802
    metaserver.loglevel: 0
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}
      config:
        metaserver.loglevel: 3
