kind: curvebs
global:
  user: curve
  ssh_port: 22
  private_key_file: /home/curve/.ssh/publish_rsa
  container_image: opencurvedocker/curvebs:v1.2
  log_dir: /home/${user}/logs/${service_role}${service_replica_sequence}
  data_dir: /home/${user}/data/${service_role}${service_replica_sequence}
  variable:
    machine1: 10.0.1.1
    machine2: 10.0.1.2
    machine3: 10.0.1.3

etcd_services:
  config:
    listen.ip: ${service_host}
    listen.port: 2380
    listen.client_port: 2379
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}

mds_services:
  config:
    listen.ip: ${service_host}
    listen.port: 6666
    listen.dummy_port: 6667
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}

chunkserver_services:
  config:
    listen.ip: ${service_host}
    listen.port: 82${format_replica_sequence}  # 8200,8201,8202
    global.enable_external_server: true
    data_dir: /data/chunkserver${service_replica_sequence}  # /data/chunkserver0, /data/chunksever1
    copysets: 100
  deploy:
    - host: ${machine1}
      replica: 3
      config:
        listen.external_ip: 10.0.2.0
    - host: ${machine2}
      replica: 3
      config:
        listen.external_ip: 10.0.2.1
    - host: ${machine3}
      replica: 3
      config:
        listen.external_ip: 10.0.2.2

snapshotclone_services:
  config:
    listen.ip: ${service_host}
    listen.port: 5555
    listen.dummy_port: 8081
    listen.proxy_port: 8080
    s3.nos_address: <>
    s3.snapshot_bucket_name: <>
    s3.ak: <>
    s3.sk: <>
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}