user: curve
ssh_port: 22
private_key_file: /home/curve/.ssh/publish_rsa
host:
  - 10.0.1.1
disk:
  - /dev/sda:/data/chunkserver0:1  # device:mount_path:format_percent
  - /dev/sdb:/data/chunkserver1:1
  - /dev/sdc:/data/chunkserver2:1
